/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'renjithgr' at '3/16/16 7:03 PM' with Gradle 2.10
 *
 * @author renjithgr, @date 3/16/16 7:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
